# This is a basic workflow to help you get started with Actions

name: Build and publish NuGet package to GitHub packages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.x'
      
    # Runs a set of commands using the runners shell
    - name: .NET pack
      run: dotnet pack -o ../drop /p:Version="0.1.$GITHUB_RUN_NUMBER"
      working-directory: src
    
    - name: Add GPR Source
      run: nuget sources Add -Name "GPR" -Source ${{ secrets.GPR_URI }} -UserName ${{ secrets.GPR_USERNAME }} -Password ${{ secrets.GITHUB_TOKEN }}
    
    - name: Push to GitHub Packages
      run: nuget push drop/*.nupkg -Source "GPR"

